// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['AddTodo'](arg1, arg2, arg3, arg4);
}

export function DeleteTodo(arg1) {
  return window['go']['app']['App']['DeleteTodo'](arg1);
}

export function GetTodos() {
  return window['go']['app']['App']['GetTodos']();
}

export function ToggleTodo(arg1) {
  return window['go']['app']['App']['ToggleTodo'](arg1);
}
