// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddTodo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteTodo(arg1:number):Promise<void>;

export function GetTodos():Promise<Array<models.Todo>>;

export function ToggleTodo(arg1:number):Promise<void>;
